on:
  workflow_call:
    inputs:
      log-level:
        required: true
        type: string
    secrets:
      GITHUB_TOKEN:
        required: true

jobs:
  call-classroom-workflow:
    uses: GittyBitch/tabot-workflows/.github/workflows/classroom.yml@main
    with:
      some-input: 1000 # Replace with actual inputs
    secrets:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Replace with actual secrets

